### ISSUE TITLE
Scrollbar contrast

### ISSUE THREAD

**Issue by robcowell** [codefriar/Codeys-in-bed-by-10#1]
Scrollbars in sidebar and editor window are hard to see for me - dark grey on slightly-less-dark grey....

![image](https://user-images.githubusercontent.com/2143167/100240192-2e7ce100-2f2a-11eb-8386-81c4684a940b.png)

**Comment by codefriar** [comment]
@robcowell  - Good catch. I'm looking for the setting that does affects that...

**Comment by robcowell** [comment]
@codefriar https://code.visualstudio.com/api/references/theme-color#scrollbar-control

**Comment by codefriar** [comment]
@robcowell  - just published 0.2.0, will probably take ~10 minutes to be seen in the marketplace.

**Comment by codefriar** [comment]
@robcowell 
![image](https://user-images.githubusercontent.com/642589/100242723-25c4e480-2f03-11eb-97ee-26130b32df71.png)

**Comment by robcowell** [comment]
Side-note, sorry - what setting did you use to get those colored brace-matching bars?

**Comment by codefriar** [comment]
@robcowell that's a combination of 3 plugins. 
1. Bracket. Pair Colorizer 2 <-- make sure to get the one with 2 in the title.
2. Indent-Rainbow
3. Indenticator 

Feel free to file an issue here if you'd like me to write up a full 'how to make this as awesome as possible' in the readme
