### ISSUE TITLE
Syntax highlighting for inline SOQL is case-dependent

### ISSUE THREAD

**Issue by robcowell** [codefriar/Codeys-in-bed-by-10#3]
Syntax highlights for SOQL are dependent on keyword capitalization

![image](https://user-images.githubusercontent.com/2143167/101401871-db604200-38ca-11eb-8a87-3713e087cffe.png)

**Comment by robcowell** [comment]
Contrived example in screenshot, I'd normally capitalize SELECT, FROM, WHERE etc.

**Comment by codefriar** [comment]
Unfortunately, the theme relies on the apex plugin to define the scope of each word / block of code and it's the apex plugin that's driving this behavior, not the theme. If you know of other themes that do not have this issue, I'm happy to investigate, but closing for now. Sorry I can't be of more help.

**Comment by robcowell** [comment]
No worries, was more “thing I spotted” than “fix this”
