### ISSUE TITLE
Keep contrasting font color on all tabs

### ISSUE THREAD

**Issue by melissajhansen** [codefriar/Codeys-in-bed-by-10#4]
I generally work with two rows open, and the file names on non-active tabs in the non-active row are almost impossible to read.  Is this a setting I haven't tweaked, or part of the theme?  

Other than this, I'm loving it so far!  

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/5881820/102541209-fd915700-4064-11eb-9318-1b76360bec56.png">

**Comment by codefriar** [comment]
@melissajhansen I totally understand and agree with you. However, I've not yet found a way to do this. I'm not giving up and will keep you updated.

**Comment by codefriar** [comment]
This has been addressed in version 0.3.2 !!
